IF NOT EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME = 'PetFinderDB')
BEGIN
	CREATE DATABASE [PetFinderDB]
END
GO

USE [PetFinderDB]
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Usuario')
BEGIN
	CREATE TABLE [dbo].[Usuario]
	(
		IdUsuario INT IDENTITY(1,1) NOT NULL,
		Avatar VARCHAR(MAX),
		Nombre VARCHAR(100) NOT NULL,
		Email VARCHAR(100) NOT NULL,
		Direccion VARCHAR(100),
		CONSTRAINT PK_Usuario PRIMARY KEY (IdUsuario)
	)
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Raza')
BEGIN
	CREATE TABLE [dbo].[Raza]
	(
		IdRaza INT IDENTITY(1,1) NOT NULL,
		Descripcion VARCHAR(50) NOT NULL,
		CONSTRAINT PK_Raza PRIMARY KEY (IdRaza)
	)
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Mascota')
BEGIN
	CREATE TABLE [dbo].[Mascota]
	(
		IdMascota INT IDENTITY(1,1) NOT NULL,
		IdUsuario INT NOT NULL FOREIGN KEY REFERENCES [dbo].[Usuario](IdUsuario),
		IdRaza INT NOT NULL FOREIGN KEY REFERENCES [dbo].[Raza](IdRaza),
		Nombre VARCHAR(50) NOT NULL,
		Perdida BIT NOT NULL,
		CONSTRAINT PK_Mascota PRIMARY KEY (IdMascota)
	)
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ImagenMascota')
BEGIN
	CREATE TABLE [dbo].[ImagenMascota]
	(
		IdImagen INT IDENTITY(1,1) NOT NULL,
		IdMascota INT NULL FOREIGN KEY REFERENCES [dbo].[Mascota](IdMascota),
		Localizacion VARCHAR(MAX),
		ImagenPath VARCHAR(MAX) NOT NULL,
		CONSTRAINT PK_ImagenMascota PRIMARY KEY (IdImagen)
	)
END
GO