//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetFinderBackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenMascota
    {
        public int IdImagen { get; set; }
        public Nullable<int> IdMascota { get; set; }
        public string Localizacion { get; set; }
        public string ImagenPath { get; set; }
    
        public virtual Mascota Mascota { get; set; }
    }
}
