//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetFinderBackOffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mascota()
        {
            this.ImagenMascota = new HashSet<ImagenMascota>();
        }
    
        public int IdMascota { get; set; }
        public int IdUsuario { get; set; }
        public int IdRaza { get; set; }
        public string Nombre { get; set; }
        public bool Perdida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenMascota> ImagenMascota { get; set; }
        public virtual Raza Raza { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
